### ISSUE TITLE
Panic on attempting to sort table with skipped u32 field

### ISSUE THREAD

**Issue by mrasmus** [Synphonyte/leptos-struct-table#18]
Running into an issue (tested on `rustc 1.78.0-nightly (256b6fb19 2024-02-06)`) with a `internal error: entered unreachable code` panic when I attempt to sort a generated table. Subsequent sorts trigger a `BorrowMutError`. Occurs in both Chrome and Firefox on MacOS.

I've got a [minimal reproduction deployed](https://mrasmus.github.io/leptos-struct-table-bug/) ([source](https://github.com/mrasmus/leptos-struct-table-bug/)) to demonstrate the issue; the crux of it is creating a table from a vec of the follow struct:

```rust

#[derive(TableRow, Clone, Debug)]
#[table(impl_vec_data_provider, 
    sortable,
)]
pub struct Item {
    #[table(skip)]
    id: u32,
    name: String,
}
```

With the `table(skip)` decorator on the `id` field, the page will panic (shown in browser console) when the header is clicked to sort the rows. I'm very green with Leptos (and Rust as a whole), so let me know if there is any additional useful detail I can provide and I'll be happy to do so.

**Comment by maccesch** [comment]
Thanks for the excellent error report! It's fixed in the just released version 0.7.1
