### ISSUE TITLE
Switch to AFIT

### ISSUE THREAD

**Issue by rupansh-gob** [Synphonyte/leptos-struct-table#19]
AFIT has been stabilized since Rust 1.75
Since we don't rely on `Send` trait, we won't need trait-variant macro either

**Comment by maccesch** [comment]
Are you talking about removing the `async_trait` macro?

**Comment by rupansh-gob** [comment]
yes

**Comment by maccesch** [comment]
Done with 7935378 and will be released in the next version very soon
