### ISSUE TITLE
Cell Renderer

### ISSUE THREAD

**Issue by ycuk** [Synphonyte/leptos-struct-table#2]
Im trying to use cell renderer.
How could I get more fields from record than only current column value?
IE: from your example:

```rust
#[derive(TableComponent, Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
#[table(sortable)]
pub struct Book {
    #[table(key)]
    pub id: u32,
    #[table(skip)]
    pub title: String,
    #[table(skip)]
    pub author: String,
    #[table(renderer = "TitleAuthorTableCellRenderer")]
    pub title_author: String,
    ...
}
```

I want to concat `title` and `author` and show in one column.

**Comment by maccesch** [comment]
You're right, this is not possible yet. I'll implement a solution ASAP!

**Comment by maccesch** [comment]
Just released v0.2.0 which implements getters.

Please check https://github.com/Synphonyte/leptos-struct-table#field-getters for how to use.

**Comment by ycuk** [comment]
Ok, thanks, the getter is good solution, but what if want to return `view!`?

```rust
view! { cx, <A href=self.id>{self.title} " (" {self.author} ")"</A> }
```

**Comment by maccesch** [comment]
In that case you would use both, a getter and a custom renderer.

The renderer will get the value that the getter returns
