### ISSUE TITLE
compile error?

### ISSUE THREAD

**Issue by skydig** [Synphonyte/leptos-struct-table#30]
compile pagination example (latest code) under windows

report:
error[E0277]: the trait bound `Authors: CellValue` is not satisfied
  --> src\models.rs:55:17
   |
55 |     pub author: Authors,
   |                 ^^^^^^^ the trait `CellValue` is not implemented for `Authors`

**Comment by lukashermansson** [comment]
Hey, there where some breaking changes in a recently merged pr, and the examples where not updated at the time of merge. 

All of the examples are fixed in this PR: https://github.com/Synphonyte/leptos-struct-table/pull/31 

I'm sorry for the inconvenience this has caused you.

**Comment by skydig** [comment]
ok. thanks.sir.

**Comment by maccesch** [comment]
@skydig Thanks for reporting!
@lukashermansson Thanks for fixing!
😄
