### ISSUE TITLE
Support stable rust

### ISSUE THREAD

**Issue by tyoeer** [Synphonyte/leptos-struct-table#35]
I'd like to use leptos-struct-table without having to switch my own project to the nightly rust compiler.

I could not easily find a documented reason for why it uses nightly, and a quick check showed that it only uses nightly in two places (in the actual library, I didn't look through the examples):
- https://github.com/Synphonyte/leptos-struct-table/blob/f30dba40fae7a2d41bc0e540f7f0c8ffdfb5d2e9/src/lib.rs#L373
  - This only gets used in modules locked behind features, e.g. https://github.com/Synphonyte/leptos-struct-table/blob/f30dba40fae7a2d41bc0e540f7f0c8ffdfb5d2e9/src/uuid.rs#L2
  - I'm not quite sure what this is used for, the modules are already locked behind the used feature flags, and stuff keeps working if I comment it all out.
- Enabling the nightly flag on Leptos itself, which is used in 4 places for shorter signal access.
  - https://github.com/Synphonyte/leptos-struct-table/blob/f30dba40fae7a2d41bc0e540f7f0c8ffdfb5d2e9/src/components/table_content.rs#L256
  - https://github.com/Synphonyte/leptos-struct-table/blob/f30dba40fae7a2d41bc0e540f7f0c8ffdfb5d2e9/src/components/table_content.rs#L669
  - https://github.com/Synphonyte/leptos-struct-table/blob/f30dba40fae7a2d41bc0e540f7f0c8ffdfb5d2e9/src/components/thead.rs#L47
  - https://github.com/Synphonyte/leptos-struct-table/blob/f30dba40fae7a2d41bc0e540f7f0c8ffdfb5d2e9/src/components/thead.rs#L53

**Comment by maccesch** [comment]
That is indeed an oversight on my part. Would you mind opening a PR?
