### ISSUE TITLE
Support impl CellValue on View without wrapper type

### ISSUE THREAD

**Issue by dt-pa** [Synphonyte/leptos-struct-table#38]
The `render_value` method returns `impl IntoView`. It'd be great if `CellValue` is implemented on `leptos_dom::View`, and we can have a field like `FieldGetter<View>` directly. It's not possible currently without an extra wrapper type because of the orphan rule.

Thank you for the great work!

**Comment by maccesch** [comment]
Thanks for the nice words. I'll see what I can do
