### ISSUE TITLE
select prop:value seems does not work

### ISSUE THREAD

**Issue by skydig** [Synphonyte/leptos-struct-table#46]
#[component]
#[allow(unused_variables)]
pub fn InputCellRenderer<F>(
    /// The class attribute for the cell element. Generated by the classes provider.
    class: String,
    /// The value to display.
    #[prop(into)]
    value: MaybeSignal<String>,
    /// Event handler called when the cell is changed. In this default renderer this will never happen.
    on_change: F,
    /// The index of the column. Starts at 0.
    index: usize,
) -> impl IntoView
where
    F: Fn(String) + 'static,
{
        view! {
            <td class=class>
               <select
                   on:change=move |ev| {}
                    prop:value=move || value.get().to_string()
             >
        .......
 the select control in one cell can not initilize itself using input value.

**Comment by maccesch** [comment]
This is not a problem with the table. I believe you have mark one option as selected.
