### ISSUE TITLE
Only first 100 rows shown, white pane below

### ISSUE THREAD

**Issue by jhoobergs** [Synphonyte/leptos-struct-table#54]
I would like to render a table with 198 rows but only the first 100 are shown while a completely empty white pane is shown below, seemingly the size of the remaining 98 rows. I added the idx to the Vec to see how many were rendered as can be seen in the image below.

![image](https://github.com/user-attachments/assets/ccfd6d90-397a-4188-a2e0-1b1c84ea366a)

The 'white pane' is one large `tr`: `<tr data-hk="1-2-0-70" style="display: block; height: 5112.55px;"></tr>`

Am I doing something wrong? I use the following code

```
<table>
    <TableContent rows />
</table>
```

I am still on v0.10.2 due to some incompatibilities with leptonic when upgrading.

EDIT: on v0.13.0 I have the same issue.

**Comment by maccesch** [comment]
For virtualization to work the scroll container needs to be known as well as its vertical size. Please have a look at the [paginated_rest_datasource example](https://github.com/Synphonyte/leptos-struct-table/tree/master/examples/paginated_rest_datasource) to see how this can be set up.
